### ISSUE TITLE
Configure check timeout

### ISSUE THREAD

**Issue by jeroen92** [choria-plugins/nrpe-agent#8]
Hi,
Is there any way to configure the timeout of an nrpe check? Currently it seems to be hardcoded in agent/nrpe.json to five seconds. Some checks however (nagios check_ntp_time for example) need more than five seconds to complete.

We're distributing the nrpe-agent choria plugin using puppet. We can of course fork this module and bump the timeout in nrpe.json, but we don't like running our forked version as it means pulling changes from upstream might get harder as time passes.

Thanks,
Jeroen

**Comment by ripienaar** [comment]
No unfortunately the timeout per agent rather than action is a very old - and probsbly not great - one. 

However you are welcome to send a PR here to update the TTLs

depending on what you are using this for exactly perhaps the new Choria Scout features would be a better match

**Comment by jeroen92** [comment]
That's a fast response, thanks! :)
Then I'll open up an MR in a second to bump this timeout to 30 seconds. We're using nrpe (and other mco/choria agents) to orchestrate automatic reprovisioning of all our servers, which triggers a lot of preflight checks using mco. I'll have a look at scout; we want to upgrade parts of our mco/puppet setup later this year. Could be nice to add Scout into that if it adds some value for our use cases.

**Comment by ripienaar** [comment]
Thanks, will try do a release today

**Comment by ripienaar** [comment]
Should be on the forge now

**Comment by jeroen92** [comment]
Thanks a bunch!
